xml/helpers.go, xml/title.go
The online xml2rfc converter at https://xml2rfc.tools.ietf.org/
requires certain XML elements to be non-empty, including various
optional parts of the authors' addresses. So this change skips
the whole of the optional element if its contents are empty.
=> Do not emit empty address components in xml output

mparser/hook.go
It will be crashed when including an empty file.
> panic: runtime error: index out of range
> 
> goroutine 1 [running]:
> github.com/mmarkdown/mmark/mparser.Initial.ReadInclude(0x0, 0xc000018740, 0x2b, 0x0, 0x0, 0xc000012820, 0x17, 0x0, 0x0, 0x0, ...)
> 	/home/mikespook/golang/3rdpkg/src/github.com/mmarkdown/mmark/mparser/hook.go:52 +0x62d
> github.com/mmarkdown/mmark/mparser.Initial.ReadInclude-fm(0x0, 0x0, 0xc000012820, 0x17, 0x0, 0x0, 0x0, 0x17, 0xc000012820, 0xc0000c9918)
It's because the `len(data)` is 0 when loading an empty file. Therefore, `len(data)-1` is `-1` which is an impossible range to a slice.
=> fixed reading 0 size file crashing

Syntax.md, testdata/caption-id.md, testdata/caption-id.xml, testdata/code-caption-id.md, testdata/code-caption-id.xml, xml/renderer.go, xml2/renderer.go
Supported by mmark1, port it to mmark2 as well (to ease transition and it's a nice feature actually)
=> allow heading-id syntax in caption

render/markdown/helpers.go, render/markdown/renderer.go, testdata/markdown/attr-list-in-def-list.fmt, testdata/markdown/def-list-para.fmt, testdata/markdown/def-list.fmt, testdata/markdown/epigraph-list.fmt, testdata/markdown/header-after-list.fmt, testdata/markdown/list-in-aside-para.fmt, testdata/markdown/list-in-aside.fmt, testdata/markdown/list-in-quote.fmt, testdata/markdown/list-indent.fmt, testdata/markdown/list-para.fmt, testdata/markdown/list-paragraph.fmt, testdata/markdown/list-start-9.fmt, testdata/markdown/list-start.fmt, testdata/markdown/list.fmt, testdata/markdown/sub-list-ending.fmt, testdata/markdown/sub-list-ending2.fmt, testdata/markdown/subfigure.fmt
This is done to recognize any block level elements correctly. We could
only do it if we detect these in a list, but this complicates the
indentation code even further, just going from 3 to 4 makes things
slightly simpler, but does make it quite spacious.
=> Indent list with 4 spaces

mast/reference/reference.go, render/mhtml/hook.go
Multiple authors in a reference were not parsed correctly, fix the
reference struct to make the author a slice.
Fixes: #53
=> Reference: allow multiple authors

mast/reference/reference.go, mast/reference/reference_test.go
This structure was incomplete; which doesn't matter if you just
reference RFCs or IDs, but does if you manually add them. Complete the
struct and add a little test.
Fixes: #61
=> Add more author elements to the reference struct

mast/reference/reference.go, mast/reference/reference_test.go
The Organization struct had two issues: one was the name of the "abbrev" attribute was incorrect; the other was the missing value in <organization>value</organization>.
This fixes #63
=> Add missing organization value in organization struct. Rename Abbrev attribute to "abbrev" to match RFC 7749.

Syntax.md, render/xml/renderer.go, testdata/image-2.md, testdata/image-2.xml, testdata/image.md, testdata/image.xml
Any alt text is used for the type attribute in rfc 7991 output.
Fixes #21
=> xml: images: use alt text for type attribute

render/xml/title.go
Although RFC 7991 says docName is deprecated it is still wanted, so add
it back in xml(3) output.
=> xml: Set docName

mast/title.go, render/xml/title.go
If empty use IETF as the default. Also only for IETF documents add the
consensus attribute.
=> Use submissionType

lang/lang.go
Language tags are described to be case-insensitive in BCP 47.
> __2.1.1.  Formatting of Language Tags__
>
> At all times, language tags and their subtags, including private use
and extensions, are to be treated as case insensitive: there exist
conventions for the capitalization of some of the subtags, but these
MUST NOT be taken to carry meaning.
>
> Thus, the tag "mn-Cyrl-MN" is not distinct from "MN-cYRL-mn" or "mN-
cYrL-Mn" (or any other combination), and each of these variations
conveys the same meaning: Mongolian written in the Cyrillic script as
used in Mongolia.
So we have to normalize the casing in order to be conformant to BCP 47. One of the easiest ways is to convert the input to the lower case, I believe.
=> Case-insensitive lang lookup for BCP 47 conformance

Syntax.md, render/man/helpers.go, testdata/man/codeblock-tab.fmt, testdata/man/codeblock-tab.md
Leaving the tabs in place made the code go all over the place. Just
convert them to spaces.
=> man: convert tabs to spaces for codeblocks

render/markdown/renderer.go, testdata/markdown/table-caption.fmt, testdata/markdown/table-caption.md
When a caption is present it needs to be next to the table, without a
newline. Fix this and add a test for it.
=> markdown: fix Table caption

mmark.go, render/man/renderer.go
Insert a bogus title if none is specified; this make the default output
for (e.g. READMEs) render correctly.
=> man: Insert mast.Title if none is seen

render/xml/renderer.go, rfc/5841.md, testdata/list.md, testdata/list.xml, testdata/liststart.xml
If a list does not contain any blocklevel elements suppress the output
of <t>'s. See https://tools.ietf.org/html/rfc7991#section-2.29 where
this is specified. The makes the outputted lists in the much tighter in
the generated xml/text/html.
Fixes: #105
=> mmark: tighten lists

render/xml/renderer.go, rfc/5841.md, testdata/list.md, testdata/list.xml, testdata/liststart.xml
Breaks XML generates, see #107
This reverts commit dfdc775543739c2a874b08cc7c18b40eb34156a7.
Fixes: #107
=> Revert "mmark: tighten lists (#106)"

mmark.1
This was removed as part of mmarkdown#97 but survived the deletion in the manpage file.
=> Remove -2 option from manpage

mparser/bibliography.go
This eases comparing XML files as the <references> don't hop around in
your locally generated XML copy.
=> Make bibliography output stable in XML

mast/reference/reference.go, mast/title.go, render/xml/title.go, rfc/3514.md
It's also used there. Extend the struct by added asciiName and
asciiValue as well.
=> Add seriesInfo to references

Syntax.md, render/xml/renderer.go
This makes including svg work for html output in xml2rfc.
=> Use extension for artwork inclusion

Syntax-images.md, Syntax.md, render/man/renderer.go, render/xml/renderer.go, testdata/artset.md, testdata/artset.xml
Add support for artset to we let xm2rfc pick the correct format when
generating output. This also fixes image output for manpage where we do
the same thing as xml2rfc, only use the ascii-art one for text output.
=> Add artset support

Syntax.md, mast/bibliography.go, mparser/bibliography.go, render/xml/bibliography.go
This add supports for referencegroups.
See https://www.rfc-editor.org/materials/FAQ-xml2rfcv3.html#section-3.8
=> reference: support referencegroup

Syntax.md, render/xml/renderer.go
In xml2rfc is a <contact> is inserted right after a <section> it is
rendered like an author. To mimic this if you only reference contact in
a paragraph, that is the first paragraph after a heading we will output
the correct XML.
=> contacts: make para only containing contacts special

Syntax.md, render/xml/renderer.go
This allows an index to be applied to the entire section instead of the
paragraph where it's entered.
=> index: allow index to be direct child of section

.github/ISSUE_TEMPLATE.md, FAQ.md, Syntax.md, render/xml/title.go
Document how this works and have some tiny fixes in the code, fyi is a
`name` in `seriesInfo` not a `status`
Fixes: #134
=> Allow FYI documents

mast/reference/reference.go, mast/reference/reference_test.go
Remove <date></date> from the generated xml.
Fixes: #138
=> reference: omit date element when not set

mmark.go
Per issue #143 
This flag is exposed with an inverted description, partly to reduce the double negatives of describing the option to the end-user.
The flag has a default of "true", which is the current mmark behavior.  A default of false or removal can be performed based on determination of impact on backwards compatibility.
=> Add flag for NoIntraEmphasis

mast/reference/reference.go
Fixes #149 where an empty `postal` entity is added to the `address`.
=> Fix a bug where an empty postal entity is added to the address

render/xml/renderer.go, testdata/liststart.xml, testdata/listtight.xml
When a list is tight, output the spacing=compact attribute in the XML
for XML2RFC.
=> Honor tight lists

go.mod, mast/bibliography.go, mast/title.go, mmark.go, mmark_man_test.go, mmark_test.go, mparser/bibliography.go, mparser/index.go, mparser/title.go, render/man/authors.go, render/man/renderer.go, render/mhtml/hook.go, render/xml/bibliography.go, render/xml/helpers.go, render/xml/renderer.go, render/xml/title.go, rfc_test.go
Because currently using `go install github.com/mmarkdown/mmark@latest` installs `v2.0.40`.
Signed-off-by: Sylvain Rabot <sylvain@abstraction.fr>
=> Rename import paths to respect go's SIV

Syntax.md, mast/title.go, mmark.go, mparser/title.go, render/xml/title.go
I believe this was added for markdown output (which is removed, because
buggy). This isn't actuall honored by the current renderers anyway, so
just remove it. Also remove 7449 XML references, as we don't support
that anymore.
=> Remove titleblock's --- trigger

mparser/bibliography.go, rfc/1.md
Make the names in rfc/1.md proper contacts and found it also created a
normative references section. This is because we don't filter
authors/contact from the reference list and hence they get outputted
there.
Fix this to check for authors and contact when gathering the informative
references.
=> Fix contacts and normative references

mmark.1, mmark.1.md
Replace en dash (U+2013) with `\-` so the NAME section can be parsed
correctly by lexgrog for query by apropos and whatis.
Fixes Lintian "bad-whatis-entry" warning:
```
W: mmark: bad-whatis-entry [usr/share/man/man1/mmark.1.gz]
N:
N:   A manual page should start with a NAME section, which lists the program
N:   name and a brief description. The NAME section is used to generate a
N:   database that can be queried by commands like apropos and whatis. You are
N:   seeing this tag because lexgrog was unable to parse the NAME section.
N:
N:   Manual pages for multiple programs, functions, or files should list each
N:   separated by a comma and a space, followed by \- and a common description.
N:
N:   Listed items may not contain any spaces. A manual page for a two-level
N:   command such as fs …
```
=> Fix NAME section in mmark.1 so it can be parsed correctly

Syntax.md, go.mod, go.sum, lang/lang.go, render/xml/renderer.go, testdata/ref.md, testdata/ref.xml
this allows setting the format attribute in a reference.
Waiting for https://github.com/gomarkdown/markdown/pull/260
=> Allow Cross Reference Suffix

render/xml/callouts.go, render/xml/renderer.go, testdata/artwork.xml, testdata/code-caption-id.xml, testdata/figure-anchor.xml, testdata/include-block-caption.xml, testdata/include-block.xml, testdata/sourcecode.xml, testdata/table-codeblock.xml
When no callouts are used, put then entire blob in a CDATA. This (at
least) allows easy extraction of data from the generated XML.
=> Use CDATA for codeblocks

render/xml/bibliography.go
Use bib.ietf.org as the base url for bib xml files.
Fixes: #192
=> Use new URL for bibliography

mast/title.go, render/xml/title.go
=> Add `sortRefs` attribute for `<rfc>` block

Syntax.md, render/xml/bibliography.go, render/xml/renderer.go, rfc/draft-citation-test.md, rfc_test.go
This fixes the citation of drafts, which is (somehow) made complex. If
the no version is given you get the latest. If you do give a version you
get *that* version. However the xref target may not include the version
and the URL of the xi:include is different depending if the version if
given or not.
Add draft-citation-test.md file to (locally) test if this all works.
Really fixes: #195
Closes: #195
=> Fix citation of drafts

render/xml/renderer.go, testdata/citation1.xml, testdata/citation2.xml, testdata/citation3.xml, testdata/citation5.xml, testdata/nl_citation1.xml, testdata/nl_citation2.xml
This ensures that section reference URLs link directly to the referenced section, instead of the top-level document.
Closes mmarkdown/mmark#205.
=> Remove `relative="#"` attribute from section citations

.github/workflows/ci.yml, .gitignore, .goreleaser.yaml
Close https://github.com/mmarkdown/mmark/issues/207
Build and release prebuilt binaries automatically with GoReleaser by CI.
- Configure GoReleaser
- Set up GitHub Actions Workflow to run GoReleaser
I ran the workflow in my fork repository for testing, and confirmed it works well.
https://github.com/suzuki-shunsuke/mmark/releases/tag/v0.1.0-3
https://github.com/suzuki-shunsuke/mmark/actions/runs/6677329544/job/18147246647
```
mmark_0.1.0-3_checksums.txt
mmark_0.1.0-3_darwin_amd64.tgz
mmark_0.1.0-3_darwin_arm64.tgz
mmark_0.1.0-3_linux_amd64.tgz
mmark_0.1.0-3_linux_arm.tgz
mmark_0.1.0-3_linux_arm64.tgz
mmark_0.1.0-3_windows_amd64.tgz
```
```console
$ tar ztvf mmark_0.1.0-3_darwin_amd64.tgz 
-rw-r--r--  0 runner docker   1362 10 28 22:56 LICENSE
-rw-r--r--  0 runner docker   4595 10 28 22:56 …
```
=> ci: set up GoReleaser

mmark.1, mmark.1.md, render/man/renderer.go
make this *always* a minus symbol, by escaping "-" when seen in the
input.
=> man: escape -

render/xml/title.go
When the series' name is RFC omit the day in the data. Unless it's a April 1st, then they do have a day.
Actually check is for 'RFC', left comment that this sounds fragile.
=> RFC date: omit day for RFC

.github/workflows/ci.yml
This should add the missing changelog. Seems like a `fetch-depth` of 0 needs to be set for the action to work properly. This is mentioned [here](https://goreleaser.com/ci/actions/#workflow) in the docs for the `goreleaser-action`.
I setup a little test repo to test these changes out. Feel free to take a look:
[CI workflow file](https://github.com/qasimwarraich/goreleaser-test/blob/main/.github/workflows/ci.yml#L18-L19)
[Releases w/ changelog](https://github.com/qasimwarraich/goreleaser-test/releases)
Resolves: #217
=> Set `fetch-depth: 0` for `actions/checkout` in `CI` pipeline
