xml/title.go

Signed-off-by: Tony Finch <dot@dotat.at>

xml2rfc months are textual not numeric

---

render/markdown/helpers.go
render/markdown/renderer.go
testdata/markdown/list-indent.fmt
testdata/markdown/list-indent.md
testdata/markdown/list-start-9.fmt
testdata/markdown/list-start-9.md
testdata/markdown/list-start.fmt
testdata/markdown/sub-list-ending.fmt
testdata/markdown/sub-list-ending2.fmt

Check the list.Start and also space the width correct for enumerated
lists.

Space lists correctly

---

render/markdown/helpers.go
render/markdown/renderer.go

Fix whitespace in tablecell rendering

---

render/markdown/renderer.go
testdata/markdown/deferred-link.fmt
testdata/markdown/deferred-link.md

Fix deferred link outputting

---

render/markdown/renderer.go

alternate between * and - in unordered lists when they are nested.

markdown: alternate listitem tokens

---

go.mod
go.sum
mparser/extensions.go
render/markdown/renderer.go

This was added upstream use it.
Fixes: #80

Default to using non-blocking-space extension

---

render/man/renderer.go
render/xml/renderer.go
render/xml2/renderer.go
testdata/nbsp.md
testdata/nbsp.xml

Fix nbsp handling in all renderers and add testcase to check that we do.

nbsp: add testdata and handle it in all renderers

---

mmark.go
render/man/renderer.go
render/mhtml/hook.go
rfc_test.go

Add biblio (the formatting and the elements is still meh - need
something more unifying accross all renderers.
Also translate Notes into the correct language, meaning for english it
is now Footnotes instead of Notes.
Fix the target output in both html and the man targets.

man: add bibliography and translate Notes

---

Syntax.md
render/xml/comment.go
rfc/8700.md
rfc/orig/rfc8700.txt

Put rfc 8700 in the mmarkified rfc. This needed a small change in the
comment handling because I didn't add the full RFC at once. Other than
that change - it flawlessly imported.

Add RFC 8700

---

render/man/renderer.go

man: support sup/sub and non blocking space

---

Syntax.md
lang/lang.go
mast/authors.go
mmark.go
render/man/authors.go
render/man/renderer.go
render/markdown/renderer.go
render/xml/renderer.go

This renders the authors (from the title block), if specified, into a
Authors section.

man pages: add author section

---

Syntax.md
render/xml/renderer.go

[@2525, section 5] is now valid.

Implement citation suffix text

---

render/man/helpers.go
render/man/renderer.go
testdata/man/codeblock.fmt
testdata/man/table-colspan.fmt
testdata/man/table-colspan.md

Add these to the table formatting.

man: implement table alignment and colspan

---

Syntax.md
mast/title.go
render/xml/renderer.go
render/xml/title.go

Implement and document on how to use contacts.

xml: implement contacts

---

Syntax.md
mast/title.go
render/xml/title.go
rfc/2100.md

Allow multiple emails

---

mast/title.go
render/xml/title.go
rfc/2100.md

Add IndexInclude

---

mast/reference/reference.go
mast/reference/reference_test.go

Add missing member to reference struct
Fixes: #137

reference: add refcontent

---

mast/reference/reference.go
mast/title.go
render/xml/title.go
rfc/feature-test.md

Found https://xml2rfc.tools.ietf.org/xml2rfc-doc.html add some of those
thing in mmark.

Add newer things

---

mmark.go

As discussed previously, here is a PR to disable intra-emphasis by default.

Disable intra-emphasis flag by default

---

README.md
Syntax.md
mparser/bibliography.go

Warn about not being able to insert the bibliography

---

README.md

There were some links that did not lead to the right heading in the article, but only went to the beginning of the article. I fixed it.

Changed links

---

render/xml/renderer.go
testdata/contact.md
testdata/contact.xml
testdata/contact1.md
testdata/contact1.xml

Actually implement the check for whitespace while inserting the contact reference. Add tests as well.
Fixes: #183

Contact rendering

---

render/xml/title.go

better diagnostic

---

Syntax.md
render/xml/bibliography.go

Fix referencing I-Ds

---

.github/workflows/ci.yml
.github/workflows/go.yml
go.mod

add release action and bump to 1.21 go

---

lang/lang.go

I am not 100% sure about the context in which UseCounter and UseTitle appear but these translations should work.
See https://mastodon.cloud/@miek/111352248195049186

lang.go: German translation
